groups:
- base_state: '

    lifx_commanders[lc_index].set_power(True)

    lifx_commanders[lc_index].set_colour("white")

    lifx_commanders[lc_index].set_luminance(1.0)

    '
  colour_temp: 3500
  match: ship-main
  max_luminance: 0.29
  rules:
  - effect: '

      lifx_commanders[lc_index].set_power(True)

      lifx_commanders[lc_index].set_luminance(1.0)

      '
    statement: ship.energy > 0.6
  - effect: '

      lifx_commanders[lc_index].set_power(True)

      lifx_commanders[lc_index].set_luminance(0.6)

      '
    statement: ship.energy < 0.4 and ship.energy >= 0.15
  - effect: '

      lifx_commanders[lc_index].set_power(True)

      lifx_commanders[lc_index].set_luminance(0.1)

      '
    statement: ship.energy < 0.15 and ship.energy >= 0.05
  - effect: lifx_commanders[lc_index].set_power(False)
    statement: ship.energy < 0.05
  - effect: '

      lifx_commanders[lc_index].set_power(True)

      lifx_commanders[lc_index].set_waveform({''waveform'': ''SAW'', ''hz'':5, ''alt_colour'':''black'',
      ''duty_cycle'':0.9})

      '
    statement: ship.hull < 0.2 and ship.hull > 0.1
  - effect: lifx_commanders[lc_index].set_power(False)
    statement: ship.hull < 0.1
- base_state: '

    lifx_commanders[lc_index].set_power(True)

    lifx_commanders[lc_index].set_colour("white")

    lifx_commanders[lc_index].set_luminance(1.0)

    '
  colour_temp: 3500
  match: ship-alert
  max_luminance: 0.29
  rules:
  - effect: lifx_commanders[lc_index].set_power(False)
    statement: ship.alert_level == 'Normal'
  - effect: '

      lifx_commanders[lc_index].set_power(True)

      lifx_commanders[lc_index].set_colour(''yellow'')

      lifx_commanders[lc_index].set_waveform({''waveform'': ''PULSE'', ''hz'': 0.5,
      ''alt_colour'': ''black'' })

      '
    statement: ship.alert_level == 'YELLOW ALERT'
  - effect: '

      lifx_commanders[lc_index].set_power(True)

      lifx_commanders[lc_index].set_colour(''red'')

      lifx_commanders[lc_index].set_waveform({''waveform'': ''PULSE'', ''hz'': 0.5,
      ''alt_colour'': ''black'' })

      '
    statement: ship.alert_level == 'RED ALERT'
poll_interval: 5
wait_for_members: true
